# Generated by Django 4.2.20 on 2025-05-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="posts/thumbnails/"
            ),
        ),
    ]
