# Generated by Django 4.2.23 on 2025-09-04 14:54

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_image_thumbnail"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="uniq_tag_name_lower",
            ),
        ),
    ]
