# Generated by Django 4.2.23 on 2025-09-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("user", "post"), name="uniq_like_user_post"
            ),
        ),
    ]
